// <auto-generated />
using System;
using DraftPuck.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DraftPuck.Infrastructure.Migrations
{
    [DbContext(typeof(DraftPuckContext))]
    [Migration("20251120024118_AddDiscordLinking")]
    partial class AddDiscordLinking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DraftPuck.Shared.Achievements.AchievementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UniqueIdentifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UniqueIdentifier")
                        .IsUnique();

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("DraftPuck.Shared.Auth.UserRefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AntiCsrfToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReasonRevoked")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRefreshTokens");
                });

            modelBuilder.Entity("DraftPuck.Shared.Banners.BannerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("AchievementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("UniqueIdentifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("DraftPuck.Shared.Lobbies.DrinkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("Assigned")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<Guid>("LobbyMemberPickId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RecipientLobbyMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LobbyMemberPickId");

                    b.HasIndex("RecipientLobbyMemberId");

                    b.ToTable("Drinks");
                });

            modelBuilder.Entity("DraftPuck.Shared.Lobbies.LobbyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GameIds")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<bool>("IsBotAutoPickingEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("PicksPerTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("DraftPuck.Shared.Lobbies.LobbyEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int?>("GameEventId")
                        .HasColumnType("int");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime?>("LastSendAttempt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LobbyEventType")
                        .HasColumnType("int");

                    b.Property<Guid?>("LobbyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LobbyMember2Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LobbyMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Player2Id")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("SendAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Subtext")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("TimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("LobbyEvents");
                });

            modelBuilder.Entity("DraftPuck.Shared.Lobbies.LobbyMemberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int?>("BotPickStyle")
                        .HasColumnType("int");

                    b.Property<bool>("IsBot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<bool>("IsRemoved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime>("Joined")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<Guid>("LobbyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LobbyId");

                    b.HasIndex("UserId");

                    b.ToTable("LobbyMembers");
                });

            modelBuilder.Entity("DraftPuck.Shared.Lobbies.LobbyMemberPickEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<Guid>("LobbyMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LobbyMemberId");

                    b.ToTable("LobbyMemberPicks");
                });

            modelBuilder.Entity("DraftPuck.Shared.Lobbies.MessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<Guid>("LobbyMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Sent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("Id");

                    b.HasIndex("LobbyMemberId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("DraftPuck.Shared.System.ErrorLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("DraftPuck.Shared.Titles.TitleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("AchievementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UniqueIdentifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("DraftPuck.Shared.Users.UserAchievementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateEarned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("DraftPuck.Shared.Users.UserBannerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("BannerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEquipped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BannerId");

                    b.HasIndex("UserId");

                    b.ToTable("UserBanners");
                });

            modelBuilder.Entity("DraftPuck.Shared.Users.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AvatarPath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ChatNotificationPreference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("DiscordUserId")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime?>("DiscordUserLinkedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrinkAwardedNotificationPreference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("DrinkReceivedNotificationPreference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FcmRegistrationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<bool>("IsBot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<bool>("IsGuest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PickingStartedNotificationPreference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DraftPuck.Shared.Users.UserTitleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("IsEquipped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TitleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTitles");
                });

            modelBuilder.Entity("DraftPuck.Shared.Auth.UserRefreshTokenEntity", b =>
                {
                    b.HasOne("DraftPuck.Shared.Users.UserEntity", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DraftPuck.Shared.Banners.BannerEntity", b =>
                {
                    b.HasOne("DraftPuck.Shared.Achievements.AchievementEntity", "Achievement")
                        .WithMany("Banners")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Achievement");
                });

            modelBuilder.Entity("DraftPuck.Shared.Lobbies.DrinkEntity", b =>
                {
                    b.HasOne("DraftPuck.Shared.Lobbies.LobbyMemberPickEntity", "LobbyMemberPick")
                        .WithMany("Drinks")
                        .HasForeignKey("LobbyMemberPickId")
                        .IsRequired()
                        .HasConstraintName("FK_Drinks_LobbyMemberPicks");

                    b.HasOne("DraftPuck.Shared.Lobbies.LobbyMemberEntity", "RecipientLobbyMember")
                        .WithMany("Drinks")
                        .HasForeignKey("RecipientLobbyMemberId")
                        .HasConstraintName("FK_Drinks_LobbyMembers");

                    b.Navigation("LobbyMemberPick");

                    b.Navigation("RecipientLobbyMember");
                });

            modelBuilder.Entity("DraftPuck.Shared.Lobbies.LobbyEntity", b =>
                {
                    b.HasOne("DraftPuck.Shared.Users.UserEntity", "CreatedByUser")
                        .WithMany("CreatedLobbies")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Lobbies_People");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("DraftPuck.Shared.Lobbies.LobbyMemberEntity", b =>
                {
                    b.HasOne("DraftPuck.Shared.Lobbies.LobbyEntity", "Lobby")
                        .WithMany("LobbyMembers")
                        .HasForeignKey("LobbyId")
                        .IsRequired()
                        .HasConstraintName("FK_LobbyMembers_Lobbies");

                    b.HasOne("DraftPuck.Shared.Users.UserEntity", "User")
                        .WithMany("LobbyMembers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_LobbyMembers_People");

                    b.Navigation("Lobby");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DraftPuck.Shared.Lobbies.LobbyMemberPickEntity", b =>
                {
                    b.HasOne("DraftPuck.Shared.Lobbies.LobbyMemberEntity", "LobbyMember")
                        .WithMany("LobbyMemberPicks")
                        .HasForeignKey("LobbyMemberId")
                        .IsRequired()
                        .HasConstraintName("FK_LobbyMemberPicks_LobbyMembers");

                    b.Navigation("LobbyMember");
                });

            modelBuilder.Entity("DraftPuck.Shared.Lobbies.MessageEntity", b =>
                {
                    b.HasOne("DraftPuck.Shared.Lobbies.LobbyMemberEntity", "LobbyMember")
                        .WithMany("Messages")
                        .HasForeignKey("LobbyMemberId")
                        .IsRequired()
                        .HasConstraintName("FK_Messages_LobbyMembers");

                    b.Navigation("LobbyMember");
                });

            modelBuilder.Entity("DraftPuck.Shared.Titles.TitleEntity", b =>
                {
                    b.HasOne("DraftPuck.Shared.Achievements.AchievementEntity", "Achievement")
                        .WithMany("Titles")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Achievement");
                });

            modelBuilder.Entity("DraftPuck.Shared.Users.UserAchievementEntity", b =>
                {
                    b.HasOne("DraftPuck.Shared.Achievements.AchievementEntity", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DraftPuck.Shared.Users.UserEntity", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DraftPuck.Shared.Users.UserBannerEntity", b =>
                {
                    b.HasOne("DraftPuck.Shared.Banners.BannerEntity", "Banner")
                        .WithMany("UserBanners")
                        .HasForeignKey("BannerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DraftPuck.Shared.Users.UserEntity", "User")
                        .WithMany("UserBanners")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Banner");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DraftPuck.Shared.Users.UserTitleEntity", b =>
                {
                    b.HasOne("DraftPuck.Shared.Titles.TitleEntity", "Title")
                        .WithMany("UserTitles")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DraftPuck.Shared.Users.UserEntity", "User")
                        .WithMany("UserTitles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DraftPuck.Shared.Achievements.AchievementEntity", b =>
                {
                    b.Navigation("Banners");

                    b.Navigation("Titles");

                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("DraftPuck.Shared.Banners.BannerEntity", b =>
                {
                    b.Navigation("UserBanners");
                });

            modelBuilder.Entity("DraftPuck.Shared.Lobbies.LobbyEntity", b =>
                {
                    b.Navigation("LobbyMembers");
                });

            modelBuilder.Entity("DraftPuck.Shared.Lobbies.LobbyMemberEntity", b =>
                {
                    b.Navigation("Drinks");

                    b.Navigation("LobbyMemberPicks");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("DraftPuck.Shared.Lobbies.LobbyMemberPickEntity", b =>
                {
                    b.Navigation("Drinks");
                });

            modelBuilder.Entity("DraftPuck.Shared.Titles.TitleEntity", b =>
                {
                    b.Navigation("UserTitles");
                });

            modelBuilder.Entity("DraftPuck.Shared.Users.UserEntity", b =>
                {
                    b.Navigation("CreatedLobbies");

                    b.Navigation("LobbyMembers");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserAchievements");

                    b.Navigation("UserBanners");

                    b.Navigation("UserTitles");
                });
#pragma warning restore 612, 618
        }
    }
}
