#!/bin/sh

cat <<EOF > /opt/app/wwwroot/env.js
window.env = {
  VITE_FIREBASE_VAPID_KEY: "${DRAFTPUCK_FIREBASE__VapidKey}",
  VITE_FIREBASE_API_KEY: "${DRAFTPUCK_FIREBASE__ApiKey}",
  VITE_FIREBASE_AUTH_DOMAIN: "${DRAFTPUCK_FIREBASE__AuthDomain}",
  VITE_FIREBASE_PROJECT_ID: "${DRAFTPUCK_FIREBASE__ProjectId}",
  VITE_FIREBASE_STORAGE_BUCKET: "${DRAFTPUCK_FIREBASE__StorageBucket}",
  VITE_FIREBASE_MESSAGING_SENDER_ID: "${DRAFTPUCK_FIREBASE__SenderId}",
  VITE_FIREBASE_APP_ID: "${DRAFTPUCK_FIREBASE__AppId}"
};
EOF

cat <<EOF > /opt/app/wwwroot/env-sw.js
self.env = {
  VITE_FIREBASE_VAPID_KEY: "${DRAFTPUCK_FIREBASE__VapidKey}",
  VITE_FIREBASE_API_KEY: "${DRAFTPUCK_FIREBASE__ApiKey}",
  VITE_FIREBASE_AUTH_DOMAIN: "${DRAFTPUCK_FIREBASE__AuthDomain}",
  VITE_FIREBASE_PROJECT_ID: "${DRAFTPUCK_FIREBASE__ProjectId}",
  VITE_FIREBASE_STORAGE_BUCKET: "${DRAFTPUCK_FIREBASE__StorageBucket}",
  VITE_FIREBASE_MESSAGING_SENDER_ID: "${DRAFTPUCK_FIREBASE__SenderId}",
  VITE_FIREBASE_APP_ID: "${DRAFTPUCK_FIREBASE__AppId}"
};
EOF

exec "$@"
