<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>a471e140-49cf-4214-96cc-d87252676d5b</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ClientApp\src\enums\botPickStyle.ts" />
    <None Remove="ClientApp\src\enums\feedItemType.ts" />
    <None Remove="ClientApp\src\enums\lobbyEventType.ts" />
    <None Remove="ClientApp\src\models\botNames.ts" />
    <None Remove="ClientApp\src\models\goalTexts.ts" />
    <None Remove="ClientApp\src\models\loadingMessages.ts" />
    <None Remove="ClientApp\src\models\lobbyEvent.d.ts" />
    <None Remove="ClientApp\src\models\nhlApi\enums\eventType.ts" />
    <None Remove="ClientApp\src\models\nhlApi\enums\gameStatusCode.ts" />
    <None Remove="ClientApp\src\models\nhlApi\enums\gameType.ts" />
    <None Remove="ClientApp\src\models\nhlApi\enums\periodType.ts" />
    <None Remove="ClientApp\src\models\nhlApi\enums\playerType.ts" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.0" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.SpaServices" Version="3.1.32" />
    <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="7.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.17.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Infrastructure\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <TypeScriptCompile Include="ClientApp\src\enums\botPickStyle.ts">
      <SubType>Code</SubType>
    </TypeScriptCompile>
    <TypeScriptCompile Include="ClientApp\src\enums\feedItemType.ts" />
    <TypeScriptCompile Include="ClientApp\src\enums\lobbyEventType.ts" />
    <TypeScriptCompile Include="ClientApp\src\models\loadingMessages.ts">
      <SubType>Code</SubType>
    </TypeScriptCompile>
    <TypeScriptCompile Include="ClientApp\src\models\botNames.ts">
      <SubType>Code</SubType>
    </TypeScriptCompile>
    <TypeScriptCompile Include="ClientApp\src\models\goalTexts.ts" />
    <TypeScriptCompile Include="ClientApp\src\models\lobbyEvent.d.ts" />
    <TypeScriptCompile Include="ClientApp\src\models\nhlApi\enums\periodType.ts">
      <SubType>Code</SubType>
    </TypeScriptCompile>
    <TypeScriptCompile Include="ClientApp\src\models\nhlApi\enums\gameStatusCode.ts">
      <SubType>Code</SubType>
    </TypeScriptCompile>
    <TypeScriptCompile Include="ClientApp\src\models\nhlApi\enums\eventType.ts">
      <SubType>Code</SubType>
    </TypeScriptCompile>
    <TypeScriptCompile Include="ClientApp\src\models\nhlApi\enums\playerType.ts">
      <SubType>Code</SubType>
    </TypeScriptCompile>
    <TypeScriptCompile Include="ClientApp\src\models\nhlApi\enums\gameType.ts" />
  </ItemGroup>

	<Target Name="ReleaseBuildWeb" BeforeTargets="BeforeBuild" Condition="'$(Configuration)' == 'Release'">
		<Message Text="Running Webpack RC Build." />
		<Exec Command="npm run build" WorkingDirectory="$(ProjectDir)ClientApp" />
	</Target>

</Project>
