import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import { loadEnv } from 'vite'

export default function fcmSwEnvPlugin(isDev: boolean) {
  const pluginName = 'rollup-plugin-fcm-sw-env'
  
  if (!isDev)
    return {
      name: pluginName
    }

  const __filename = fileURLToPath(import.meta.url)
  const __dirname = path.dirname(__filename)

  const env = loadEnv('development', process.cwd(), '')
  const swEnvVars = Object.keys(env).filter(key => key.startsWith('VITE_FIREBASE_'));
  const envContent = swEnvVars.map(key => `\t${key}: "${env[key]}"`).join(',\n');

  const envSwCode = 
    '// IMPORTANT: This file is generated by vite-plugin-fcm-sw-env. Do not modify.\n\n' +
    'self.env = {\n' + 
    envContent + 
    '\n};\n';

  const envSwOutputPath = path.resolve('public', './env-sw.js');
  fs.writeFileSync(envSwOutputPath, envSwCode);
  
  const srcDir = path.resolve(__dirname, '../src')
  const fcmSwCode = fs.readFileSync(`${srcDir}/firebase-messaging-sw.js`, 'utf8')
  const transformedCode = fcmSwCode.replace(new RegExp(`self.env.(\\w+)`, 'g'), (_, varName) => `"${env[varName]}"`)
  
  const finalCode =
    '// IMPORTANT: This file only exists for dev mode purposes. Do not modify this file. Any changes should be made in `src/firebase-messaging-sw.js`.\n\n' +
    transformedCode

  const outputPath = path.resolve('public', './firebase-messaging-sw.js')
  fs.writeFileSync(outputPath, finalCode)

  return {
    name: pluginName
  }
}