/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Conference } from './conference';
/**
 * 
 * @export
 * @interface Conferences
 */
export interface Conferences {
    /**
     * 
     * @type {string}
     * @memberof Conferences
     */
    copyright?: string;
    /**
     * 
     * @type {Array<Conference>}
     * @memberof Conferences
     */
    teams?: Array<Conference>;
}
