/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DivisionConference } from './division-conference';
/**
 * 
 * @export
 * @interface Division
 */
export interface Division {
    /**
     * 
     * @type {number}
     * @memberof Division
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Division
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Division
     */
    link?: string;
    /**
     * 
     * @type {string}
     * @memberof Division
     */
    abbreviation?: string;
    /**
     * 
     * @type {DivisionConference}
     * @memberof Division
     */
    conference?: DivisionConference;
    /**
     * 
     * @type {boolean}
     * @memberof Division
     */
    active?: boolean;
}
