/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Division } from './division';
/**
 * 
 * @export
 * @interface Divisions
 */
export interface Divisions {
    /**
     * 
     * @type {string}
     * @memberof Divisions
     */
    copyright?: string;
    /**
     * 
     * @type {Array<Division>}
     * @memberof Divisions
     */
    teams?: Array<Division>;
}
