/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GamePlayAbout } from './game-play-about';
import { GamePlayCoordinates } from './game-play-coordinates';
import { GamePlayPlayers } from './game-play-players';
import { GamePlayResult } from './game-play-result';
import { GamePlayTeam } from './game-play-team';
/**
 * 
 * @export
 * @interface GamePlay
 */
export interface GamePlay {
    /**
     * 
     * @type {Array<GamePlayPlayers>}
     * @memberof GamePlay
     */
    players?: Array<GamePlayPlayers>;
    /**
     * 
     * @type {GamePlayResult}
     * @memberof GamePlay
     */
    result?: GamePlayResult;
    /**
     * 
     * @type {GamePlayAbout}
     * @memberof GamePlay
     */
    about?: GamePlayAbout;
    /**
     * 
     * @type {GamePlayCoordinates}
     * @memberof GamePlay
     */
    coordinates?: GamePlayCoordinates;
    /**
     * 
     * @type {GamePlayTeam}
     * @memberof GamePlay
     */
    team?: GamePlayTeam;
    /**
     * 
     * @type {number}
     * @memberof GamePlay
     */
    gamePk?: number;
}
