/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GameBoxscoreTeamCoaches } from './game-boxscore-team-coaches';
import { GameBoxscoreTeamOnIcePlus } from './game-boxscore-team-on-ice-plus';
import { GameBoxscoreTeamPlayers } from './game-boxscore-team-players';
import { GameBoxscoreTeamTeam } from './game-boxscore-team-team';
import { GameBoxscoreTeamTeamStats } from './game-boxscore-team-team-stats';
/**
 * 
 * @export
 * @interface GameBoxscoreTeam
 */
export interface GameBoxscoreTeam {
    /**
     * 
     * @type {GameBoxscoreTeamTeam}
     * @memberof GameBoxscoreTeam
     */
    team?: GameBoxscoreTeamTeam;
    /**
     * 
     * @type {GameBoxscoreTeamTeamStats}
     * @memberof GameBoxscoreTeam
     */
    teamStats?: GameBoxscoreTeamTeamStats;
    /**
     * 
     * @type {GameBoxscoreTeamPlayers}
     * @memberof GameBoxscoreTeam
     */
    players?: GameBoxscoreTeamPlayers;
    /**
     * 
     * @type {Array<number>}
     * @memberof GameBoxscoreTeam
     */
    goalies?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof GameBoxscoreTeam
     */
    skaters?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof GameBoxscoreTeam
     */
    onIce?: Array<number>;
    /**
     * 
     * @type {Array<GameBoxscoreTeamOnIcePlus>}
     * @memberof GameBoxscoreTeam
     */
    onIcePlus?: Array<GameBoxscoreTeamOnIcePlus>;
    /**
     * 
     * @type {Array<number>}
     * @memberof GameBoxscoreTeam
     */
    scratches?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof GameBoxscoreTeam
     */
    penaltyBox?: Array<number>;
    /**
     * 
     * @type {Array<GameBoxscoreTeamCoaches>}
     * @memberof GameBoxscoreTeam
     */
    coaches?: Array<GameBoxscoreTeamCoaches>;
}
