/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GameBoxscoreTeamPlayersStatsSkaterStats
 */
export interface GameBoxscoreTeamPlayersStatsSkaterStats {
    /**
     * 
     * @type {string}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    timeOnIce?: string;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    assists?: number;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    goals?: number;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    shots?: number;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    hits?: number;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    powerPlayGoals?: number;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    powerPlayAssists?: number;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    penaltyMinutes?: number;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    faceOffWins?: number;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    faceoffTaken?: number;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    takeaways?: number;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    giveaways?: number;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    shortHandedGoals?: number;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    shortHandedAssists?: number;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    blocked?: number;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    plusMinus?: number;
    /**
     * 
     * @type {string}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    evenTimeOnIce?: string;
    /**
     * 
     * @type {string}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    powerPlayTimeOnIce?: string;
    /**
     * 
     * @type {string}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    shortHandedTimeOnIce?: string;
}
