/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GameBoxscoreTeamTeam } from './game-boxscore-team-team';
/**
 * 
 * @export
 * @interface GameLinescoreTeam
 */
export interface GameLinescoreTeam {
    /**
     * 
     * @type {GameBoxscoreTeamTeam}
     * @memberof GameLinescoreTeam
     */
    team?: GameBoxscoreTeamTeam;
    /**
     * 
     * @type {number}
     * @memberof GameLinescoreTeam
     */
    goals?: number;
    /**
     * 
     * @type {number}
     * @memberof GameLinescoreTeam
     */
    shotsOnGoal?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GameLinescoreTeam
     */
    goaliePulled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GameLinescoreTeam
     */
    numSkaters?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GameLinescoreTeam
     */
    powerPlay?: boolean;
}
