/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GameHighlightType } from './game-highlight-type';
/**
 * 
 * @export
 * @interface GameHighlights
 */
export interface GameHighlights {
    /**
     * 
     * @type {GameHighlightType}
     * @memberof GameHighlights
     */
    scoreboard?: GameHighlightType;
    /**
     * 
     * @type {GameHighlightType}
     * @memberof GameHighlights
     */
    gameCenter?: GameHighlightType;
}
