/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GameEditorialTokenData
 */
export interface GameEditorialTokenData {
    /**
     * 
     * @type {string}
     * @memberof GameEditorialTokenData
     */
    tokenGUID?: string;
    /**
     * 
     * @type {string}
     * @memberof GameEditorialTokenData
     */
    type?: GameEditorialTokenDataTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GameEditorialTokenData
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GameEditorialTokenData
     */
    teamId?: string;
    /**
     * 
     * @type {string}
     * @memberof GameEditorialTokenData
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof GameEditorialTokenData
     */
    seoName?: string;
    /**
     * 
     * @type {string}
     * @memberof GameEditorialTokenData
     */
    href?: string;
    /**
     * 
     * @type {string}
     * @memberof GameEditorialTokenData
     */
    hrefMobile?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum GameEditorialTokenDataTypeEnum {
    HyperLink = 'hyperLink',
    PlayerCard = 'playerCard'
}

