/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GameBoxscore } from './game-boxscore';
import { GameLinescore } from './game-linescore';
import { GameLiveDataDecisions } from './game-live-data-decisions';
import { GameLiveDataPlays } from './game-live-data-plays';
/**
 * 
 * @export
 * @interface GameLiveData
 */
export interface GameLiveData {
    /**
     * 
     * @type {GameLiveDataPlays}
     * @memberof GameLiveData
     */
    plays?: GameLiveDataPlays;
    /**
     * 
     * @type {GameLinescore}
     * @memberof GameLiveData
     */
    linescore?: GameLinescore;
    /**
     * 
     * @type {GameBoxscore}
     * @memberof GameLiveData
     */
    boxscore?: GameBoxscore;
    /**
     * 
     * @type {GameLiveDataDecisions}
     * @memberof GameLiveData
     */
    decisions?: GameLiveDataDecisions;
}
