/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GameBoxscoreTeamPlayersPerson } from './game-boxscore-team-players-person';
import { GameBoxscoreTeamPlayersPosition } from './game-boxscore-team-players-position';
import { GameBoxscoreTeamPlayersStats } from './game-boxscore-team-players-stats';
/**
 * 
 * @export
 * @interface GameBoxscoreTeamPlayers
 */
export interface GameBoxscoreTeamPlayers {
    /**
     * 
     * @type {GameBoxscoreTeamPlayersPerson}
     * @memberof GameBoxscoreTeamPlayers
     */
    person?: GameBoxscoreTeamPlayersPerson;
    /**
     * 
     * @type {string}
     * @memberof GameBoxscoreTeamPlayers
     */
    jerseyNumber?: string;
    /**
     * 
     * @type {GameBoxscoreTeamPlayersPosition}
     * @memberof GameBoxscoreTeamPlayers
     */
    position?: GameBoxscoreTeamPlayersPosition;
    /**
     * 
     * @type {GameBoxscoreTeamPlayersStats}
     * @memberof GameBoxscoreTeamPlayers
     */
    stats?: GameBoxscoreTeamPlayersStats;
}
