/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GamePeriodAway } from './game-period-away';
import { GamePeriodHome } from './game-period-home';
/**
 * 
 * @export
 * @interface GamePeriod
 */
export interface GamePeriod {
    /**
     * 
     * @type {string}
     * @memberof GamePeriod
     */
    periodType?: string;
    /**
     * 
     * @type {Date}
     * @memberof GamePeriod
     */
    startTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GamePeriod
     */
    endTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof GamePeriod
     */
    num?: number;
    /**
     * 
     * @type {string}
     * @memberof GamePeriod
     */
    ordinalNum?: string;
    /**
     * 
     * @type {GamePeriodHome}
     * @memberof GamePeriod
     */
    home?: GamePeriodHome;
    /**
     * 
     * @type {GamePeriodAway}
     * @memberof GamePeriod
     */
    away?: GamePeriodAway;
}
