/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GameLiveDataPlaysPlaysByPeriod } from './game-live-data-plays-plays-by-period';
import { GamePlay } from './game-play';
/**
 * 
 * @export
 * @interface GameLiveDataPlays
 */
export interface GameLiveDataPlays {
    /**
     * 
     * @type {Array<GamePlay>}
     * @memberof GameLiveDataPlays
     */
    allPlays?: Array<GamePlay>;
    /**
     * 
     * @type {Array<number>}
     * @memberof GameLiveDataPlays
     */
    scoringPlays?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof GameLiveDataPlays
     */
    penaltyPlays?: Array<number>;
    /**
     * 
     * @type {Array<GameLiveDataPlaysPlaysByPeriod>}
     * @memberof GameLiveDataPlays
     */
    playsByPeriod?: Array<GameLiveDataPlaysPlaysByPeriod>;
    /**
     * 
     * @type {GamePlay}
     * @memberof GameLiveDataPlays
     */
    currentPlay?: GamePlay;
}
