/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GameGameData } from './game-game-data';
import { GameLiveData } from './game-live-data';
import { GameMetaData } from './game-meta-data';
/**
 * 
 * @export
 * @interface Game
 */
export interface Game {
    /**
     * 
     * @type {string}
     * @memberof Game
     */
    copyright?: string;
    /**
     * 
     * @type {number}
     * @memberof Game
     */
    gamePk?: number;
    /**
     * 
     * @type {string}
     * @memberof Game
     */
    link?: string;
    /**
     * 
     * @type {GameMetaData}
     * @memberof Game
     */
    metaData?: GameMetaData;
    /**
     * 
     * @type {GameGameData}
     * @memberof Game
     */
    gameData?: GameGameData;
    /**
     * 
     * @type {GameLiveData}
     * @memberof Game
     */
    liveData?: GameLiveData;
}
