/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GameEditorialKeyword } from './game-editorial-keyword';
import { GameHighlightPlaybacks } from './game-highlight-playbacks';
import { Photo } from './photo';
/**
 * 
 * @export
 * @interface GameHighlight
 */
export interface GameHighlight {
    /**
     * 
     * @type {string}
     * @memberof GameHighlight
     */
    type?: GameHighlightTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GameHighlight
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof GameHighlight
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof GameHighlight
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof GameHighlight
     */
    blurb?: string;
    /**
     * 
     * @type {string}
     * @memberof GameHighlight
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof GameHighlight
     */
    duration?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GameHighlight
     */
    authFlow?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GameHighlight
     */
    mediaPlaybackId?: string;
    /**
     * 
     * @type {string}
     * @memberof GameHighlight
     */
    mediaState?: string;
    /**
     * 
     * @type {Array<GameEditorialKeyword>}
     * @memberof GameHighlight
     */
    keywords?: Array<GameEditorialKeyword>;
    /**
     * 
     * @type {Photo}
     * @memberof GameHighlight
     */
    image?: Photo;
    /**
     * 
     * @type {Array<GameHighlightPlaybacks>}
     * @memberof GameHighlight
     */
    playbacks?: Array<GameHighlightPlaybacks>;
}

/**
    * @export
    * @enum {string}
    */
export enum GameHighlightTypeEnum {
    Video = 'video'
}

