/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GameEditorialContributor } from './game-editorial-contributor';
import { GameEditorialKeyword } from './game-editorial-keyword';
import { GameEditorialMedia } from './game-editorial-media';
import { GameEditorialTokenData } from './game-editorial-token-data';
/**
 * 
 * @export
 * @interface GameEditorial
 */
export interface GameEditorial {
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    state?: string;
    /**
     * 
     * @type {Date}
     * @memberof GameEditorial
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    headline?: string;
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    subhead?: string;
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    seoTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    seoDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    seoKeywords?: string;
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    slug?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GameEditorial
     */
    commenting?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    tagline?: string;
    /**
     * 
     * @type {GameEditorialTokenData}
     * @memberof GameEditorial
     */
    tokenData?: GameEditorialTokenData;
    /**
     * 
     * @type {GameEditorialContributor}
     * @memberof GameEditorial
     */
    contributor?: GameEditorialContributor;
    /**
     * 
     * @type {Array<GameEditorialKeyword>}
     * @memberof GameEditorial
     */
    keywordsDisplay?: Array<GameEditorialKeyword>;
    /**
     * 
     * @type {Array<GameEditorialKeyword>}
     * @memberof GameEditorial
     */
    keywordsAll?: Array<GameEditorialKeyword>;
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    approval?: string;
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    dataURI?: string;
    /**
     * 
     * @type {GameEditorialKeyword}
     * @memberof GameEditorial
     */
    primaryKeyword?: GameEditorialKeyword;
    /**
     * 
     * @type {GameEditorialMedia}
     * @memberof GameEditorial
     */
    media?: GameEditorialMedia;
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    preview?: string;
}
