/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GameGameDataDatetime } from './game-game-data-datetime';
import { GameGameDataGame } from './game-game-data-game';
import { GameGameDataStatus } from './game-game-data-status';
import { GameGameDataTeams } from './game-game-data-teams';
import { GameGameDataVenue } from './game-game-data-venue';
import { Player } from './player';
/**
 * 
 * @export
 * @interface GameGameData
 */
export interface GameGameData {
    /**
     * 
     * @type {GameGameDataGame}
     * @memberof GameGameData
     */
    game?: GameGameDataGame;
    /**
     * 
     * @type {GameGameDataDatetime}
     * @memberof GameGameData
     */
    datetime?: GameGameDataDatetime;
    /**
     * 
     * @type {GameGameDataStatus}
     * @memberof GameGameData
     */
    status?: GameGameDataStatus;
    /**
     * 
     * @type {GameGameDataTeams}
     * @memberof GameGameData
     */
    teams?: GameGameDataTeams;
    /**
     * 
     * @type {Player}
     * @memberof GameGameData
     */
    players?: Player;
    /**
     * 
     * @type {GameGameDataVenue}
     * @memberof GameGameData
     */
    venue?: GameGameDataVenue;
}
