/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GameBoxscoreTeams } from './game-boxscore-teams';
import { GameOfficial } from './game-official';
/**
 * 
 * @export
 * @interface GameBoxscore
 */
export interface GameBoxscore {
    /**
     * 
     * @type {GameBoxscoreTeams}
     * @memberof GameBoxscore
     */
    teams?: GameBoxscoreTeams;
    /**
     * 
     * @type {Array<GameOfficial>}
     * @memberof GameBoxscore
     */
    officials?: Array<GameOfficial>;
}
