/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GameContentEditorial } from './game-content-editorial';
import { GameContentHighlights } from './game-content-highlights';
import { GameContentMedia } from './game-content-media';
/**
 * 
 * @export
 * @interface GameContent
 */
export interface GameContent {
    /**
     * 
     * @type {string}
     * @memberof GameContent
     */
    copyright?: string;
    /**
     * 
     * @type {string}
     * @memberof GameContent
     */
    link?: string;
    /**
     * 
     * @type {GameContentEditorial}
     * @memberof GameContent
     */
    editorial?: GameContentEditorial;
    /**
     * 
     * @type {GameContentMedia}
     * @memberof GameContent
     */
    media?: GameContentMedia;
    /**
     * 
     * @type {GameContentHighlights}
     * @memberof GameContent
     */
    highlights?: GameContentHighlights;
}
