/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GameLinescoreTeam } from './game-linescore-team';
/**
 * 
 * @export
 * @interface GameLinescoreTeams
 */
export interface GameLinescoreTeams {
    /**
     * 
     * @type {GameLinescoreTeam}
     * @memberof GameLinescoreTeams
     */
    home?: GameLinescoreTeam;
    /**
     * 
     * @type {GameLinescoreTeam}
     * @memberof GameLinescoreTeams
     */
    away?: GameLinescoreTeam;
}
