/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GameMediaNHLTVItems
 */
export interface GameMediaNHLTVItems {
    /**
     * 
     * @type {string}
     * @memberof GameMediaNHLTVItems
     */
    guid?: string;
    /**
     * 
     * @type {string}
     * @memberof GameMediaNHLTVItems
     */
    mediaState?: string;
    /**
     * 
     * @type {string}
     * @memberof GameMediaNHLTVItems
     */
    mediaPlaybackId?: string;
    /**
     * 
     * @type {string}
     * @memberof GameMediaNHLTVItems
     */
    mediaFeedType?: string;
    /**
     * 
     * @type {string}
     * @memberof GameMediaNHLTVItems
     */
    callLetters?: string;
    /**
     * 
     * @type {string}
     * @memberof GameMediaNHLTVItems
     */
    eventId?: string;
    /**
     * 
     * @type {string}
     * @memberof GameMediaNHLTVItems
     */
    language?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GameMediaNHLTVItems
     */
    freeGame?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GameMediaNHLTVItems
     */
    feedName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GameMediaNHLTVItems
     */
    gamePlus?: boolean;
}
