/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GameEditorials } from './game-editorials';
/**
 * 
 * @export
 * @interface GameContentEditorial
 */
export interface GameContentEditorial {
    /**
     * 
     * @type {GameEditorials}
     * @memberof GameContentEditorial
     */
    preview?: GameEditorials;
    /**
     * 
     * @type {GameEditorials}
     * @memberof GameContentEditorial
     */
    articles?: GameEditorials;
    /**
     * 
     * @type {GameEditorials}
     * @memberof GameContentEditorial
     */
    recap?: GameEditorials;
}
