/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GameBoxscoreTeamPerson } from './game-boxscore-team-person';
import { GameBoxscoreTeamPosition } from './game-boxscore-team-position';
/**
 * 
 * @export
 * @interface GameBoxscoreTeamCoaches
 */
export interface GameBoxscoreTeamCoaches {
    /**
     * 
     * @type {GameBoxscoreTeamPerson}
     * @memberof GameBoxscoreTeamCoaches
     */
    person?: GameBoxscoreTeamPerson;
    /**
     * 
     * @type {GameBoxscoreTeamPosition}
     * @memberof GameBoxscoreTeamCoaches
     */
    position?: GameBoxscoreTeamPosition;
}
