/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GameHighlight } from './game-highlight';
/**
 * 
 * @export
 * @interface GameContentMediaMilestonesItems
 */
export interface GameContentMediaMilestonesItems {
    /**
     * 
     * @type {string}
     * @memberof GameContentMediaMilestonesItems
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof GameContentMediaMilestonesItems
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof GameContentMediaMilestonesItems
     */
    type?: GameContentMediaMilestonesItemsTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof GameContentMediaMilestonesItems
     */
    timeAbsolute?: Date;
    /**
     * 
     * @type {string}
     * @memberof GameContentMediaMilestonesItems
     */
    timeOffset?: string;
    /**
     * 
     * @type {string}
     * @memberof GameContentMediaMilestonesItems
     */
    period?: string;
    /**
     * 
     * @type {string}
     * @memberof GameContentMediaMilestonesItems
     */
    statsEventId?: string;
    /**
     * 
     * @type {string}
     * @memberof GameContentMediaMilestonesItems
     */
    teamId?: string;
    /**
     * 
     * @type {string}
     * @memberof GameContentMediaMilestonesItems
     */
    playerId?: string;
    /**
     * 
     * @type {string}
     * @memberof GameContentMediaMilestonesItems
     */
    periodTime?: string;
    /**
     * 
     * @type {string}
     * @memberof GameContentMediaMilestonesItems
     */
    ordinalNum?: string;
    /**
     * 
     * @type {GameHighlight}
     * @memberof GameContentMediaMilestonesItems
     */
    highlight?: GameHighlight;
}

/**
    * @export
    * @enum {string}
    */
export enum GameContentMediaMilestonesItemsTypeEnum {
    BROADCASTSTART = 'BROADCAST_START',
    BROADCASTEND = 'BROADCAST_END',
    GOAL = 'GOAL',
    PERIODEND = 'PERIOD_END',
    PERIODSTART = 'PERIOD_START',
    SHOT = 'SHOT'
}

