/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GameMediaAudioItems } from './game-media-audio-items';
/**
 * 
 * @export
 * @interface GameMediaAudio
 */
export interface GameMediaAudio {
    /**
     * 
     * @type {string}
     * @memberof GameMediaAudio
     */
    title?: string;
    /**
     * 
     * @type {Array<GameMediaAudioItems>}
     * @memberof GameMediaAudio
     */
    items?: Array<GameMediaAudioItems>;
}
