/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GamePlayPlayer } from './game-play-player';
/**
 * 
 * @export
 * @interface GamePlayPlayers
 */
export interface GamePlayPlayers {
    /**
     * 
     * @type {GamePlayPlayer}
     * @memberof GamePlayPlayers
     */
    player?: GamePlayPlayer;
    /**
     * 
     * @type {string}
     * @memberof GamePlayPlayers
     */
    playerType?: string;
    /**
     * 
     * @type {number}
     * @memberof GamePlayPlayers
     */
    seasonTotal?: number;
}
