/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GameContentMediaMilestonesItems } from './game-content-media-milestones-items';
/**
 * 
 * @export
 * @interface GameContentMediaMilestones
 */
export interface GameContentMediaMilestones {
    /**
     * 
     * @type {string}
     * @memberof GameContentMediaMilestones
     */
    title?: GameContentMediaMilestonesTitleEnum;
    /**
     * 
     * @type {Date}
     * @memberof GameContentMediaMilestones
     */
    streamStart?: Date;
    /**
     * 
     * @type {Array<GameContentMediaMilestonesItems>}
     * @memberof GameContentMediaMilestones
     */
    items?: Array<GameContentMediaMilestonesItems>;
}

/**
    * @export
    * @enum {string}
    */
export enum GameContentMediaMilestonesTitleEnum {
    Milestones = 'Milestones'
}

