/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GameLinescoreIntermissionInfo } from './game-linescore-intermission-info';
import { GameLinescorePowerPlayInfo } from './game-linescore-power-play-info';
import { GameLinescoreShootoutInfo } from './game-linescore-shootout-info';
import { GameLinescoreTeams } from './game-linescore-teams';
import { GamePeriod } from './game-period';
/**
 * 
 * @export
 * @interface GameLinescore
 */
export interface GameLinescore {
    /**
     * 
     * @type {number}
     * @memberof GameLinescore
     */
    currentPeriod?: number;
    /**
     * 
     * @type {string}
     * @memberof GameLinescore
     */
    currentPeriodOrdinal?: string;
    /**
     * 
     * @type {string}
     * @memberof GameLinescore
     */
    currentPeriodTimeRemaining?: string;
    /**
     * 
     * @type {Array<GamePeriod>}
     * @memberof GameLinescore
     */
    periods?: Array<GamePeriod>;
    /**
     * 
     * @type {GameLinescoreShootoutInfo}
     * @memberof GameLinescore
     */
    shootoutInfo?: GameLinescoreShootoutInfo;
    /**
     * 
     * @type {GameLinescoreTeams}
     * @memberof GameLinescore
     */
    teams?: GameLinescoreTeams;
    /**
     * 
     * @type {string}
     * @memberof GameLinescore
     */
    powerPlayStrength?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GameLinescore
     */
    hasShootout?: boolean;
    /**
     * 
     * @type {GameLinescoreIntermissionInfo}
     * @memberof GameLinescore
     */
    intermissionInfo?: GameLinescoreIntermissionInfo;
    /**
     * 
     * @type {GameLinescorePowerPlayInfo}
     * @memberof GameLinescore
     */
    powerPlayInfo?: GameLinescorePowerPlayInfo;
}
