/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GamePlayAboutGoals } from './game-play-about-goals';
/**
 * 
 * @export
 * @interface GamePlayAbout
 */
export interface GamePlayAbout {
    /**
     * 
     * @type {number}
     * @memberof GamePlayAbout
     */
    eventIdx?: number;
    /**
     * 
     * @type {number}
     * @memberof GamePlayAbout
     */
    eventId?: number;
    /**
     * 
     * @type {number}
     * @memberof GamePlayAbout
     */
    period?: number;
    /**
     * 
     * @type {string}
     * @memberof GamePlayAbout
     */
    periodType?: string;
    /**
     * 
     * @type {string}
     * @memberof GamePlayAbout
     */
    ordinalNum?: string;
    /**
     * 
     * @type {string}
     * @memberof GamePlayAbout
     */
    periodTime?: string;
    /**
     * 
     * @type {string}
     * @memberof GamePlayAbout
     */
    periodTimeRemaining?: string;
    /**
     * 
     * @type {Date}
     * @memberof GamePlayAbout
     */
    dateTime?: Date;
    /**
     * 
     * @type {GamePlayAboutGoals}
     * @memberof GamePlayAbout
     */
    goals?: GamePlayAboutGoals;
}
