/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GameBoxscoreTeamTeamStatsTeamSkaterStats
 */
export interface GameBoxscoreTeamTeamStatsTeamSkaterStats {
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamTeamStatsTeamSkaterStats
     */
    goals?: number;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamTeamStatsTeamSkaterStats
     */
    pim?: number;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamTeamStatsTeamSkaterStats
     */
    shots?: number;
    /**
     * 
     * @type {string}
     * @memberof GameBoxscoreTeamTeamStatsTeamSkaterStats
     */
    powerPlayPercentage?: string;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamTeamStatsTeamSkaterStats
     */
    powerPlayGoals?: number;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamTeamStatsTeamSkaterStats
     */
    powerPlayOpportunities?: number;
    /**
     * 
     * @type {string}
     * @memberof GameBoxscoreTeamTeamStatsTeamSkaterStats
     */
    faceOffWinPercentage?: string;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamTeamStatsTeamSkaterStats
     */
    blocked?: number;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamTeamStatsTeamSkaterStats
     */
    takeaways?: number;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamTeamStatsTeamSkaterStats
     */
    giveaways?: number;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamTeamStatsTeamSkaterStats
     */
    hits?: number;
}
