/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PhotoCuts } from './photo-cuts';
/**
 * 
 * @export
 * @interface Photo
 */
export interface Photo {
    /**
     * 
     * @type {string}
     * @memberof Photo
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof Photo
     */
    altText?: string;
    /**
     * 
     * @type {PhotoCuts}
     * @memberof Photo
     */
    cuts?: PhotoCuts;
}
