/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PlayerStatsSplits } from './player-stats-splits';
import { PlayerStatsType } from './player-stats-type';
/**
 * 
 * @export
 * @interface PlayerStatsStats
 */
export interface PlayerStatsStats {
    /**
     * 
     * @type {PlayerStatsType}
     * @memberof PlayerStatsStats
     */
    type?: PlayerStatsType;
    /**
     * 
     * @type {Array<PlayerStatsSplits>}
     * @memberof PlayerStatsStats
     */
    splits?: Array<PlayerStatsSplits>;
}
