/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PlayerStatsStats } from './player-stats-stats';
/**
 * 
 * @export
 * @interface PlayerStats
 */
export interface PlayerStats {
    /**
     * 
     * @type {string}
     * @memberof PlayerStats
     */
    copyright?: string;
    /**
     * 
     * @type {Array<PlayerStatsStats>}
     * @memberof PlayerStats
     */
    stats?: Array<PlayerStatsStats>;
}
