/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DivisionConference } from './division-conference';
import { DraftTeam } from './draft-team';
import { PlayerStatsOpponentDivision } from './player-stats-opponent-division';
import { PlayerStatsStat } from './player-stats-stat';
/**
 * 
 * @export
 * @interface PlayerStatsSplits
 */
export interface PlayerStatsSplits {
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsSplits
     */
    season?: string;
    /**
     * 
     * @type {PlayerStatsStat}
     * @memberof PlayerStatsSplits
     */
    stat?: PlayerStatsStat;
    /**
     * 
     * @type {boolean}
     * @memberof PlayerStatsSplits
     */
    isHome?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PlayerStatsSplits
     */
    isWin?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PlayerStatsSplits
     */
    isOT?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsSplits
     */
    month?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsSplits
     */
    dayOfWeek?: number;
    /**
     * 
     * @type {DraftTeam}
     * @memberof PlayerStatsSplits
     */
    opponent?: DraftTeam;
    /**
     * 
     * @type {PlayerStatsOpponentDivision}
     * @memberof PlayerStatsSplits
     */
    opponentDivision?: PlayerStatsOpponentDivision;
    /**
     * 
     * @type {DivisionConference}
     * @memberof PlayerStatsSplits
     */
    opponentConference?: DivisionConference;
}
