/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Player } from './player';
/**
 * 
 * @export
 * @interface Players
 */
export interface Players {
    /**
     * 
     * @type {string}
     * @memberof Players
     */
    copyright: string;
    /**
     * 
     * @type {Array<Player>}
     * @memberof Players
     */
    teams?: Array<Player>;
}
