/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DraftProspectPrimaryPosition } from './draft-prospect-primary-position';
import { PlayerCurrentTeam } from './player-current-team';
/**
 * 
 * @export
 * @interface Player
 */
export interface Player {
    /**
     * 
     * @type {number}
     * @memberof Player
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Player
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof Player
     */
    link?: string;
    /**
     * 
     * @type {string}
     * @memberof Player
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof Player
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof Player
     */
    primaryNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof Player
     */
    birthDate?: string;
    /**
     * 
     * @type {number}
     * @memberof Player
     */
    currentAge?: number;
    /**
     * 
     * @type {string}
     * @memberof Player
     */
    birthCity?: string;
    /**
     * 
     * @type {string}
     * @memberof Player
     */
    birthStateProvince?: string;
    /**
     * 
     * @type {string}
     * @memberof Player
     */
    birthCountry?: string;
    /**
     * 
     * @type {string}
     * @memberof Player
     */
    nationality?: string;
    /**
     * 
     * @type {string}
     * @memberof Player
     */
    height?: string;
    /**
     * 
     * @type {number}
     * @memberof Player
     */
    weight?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Player
     */
    active?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Player
     */
    alternateCaptain?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Player
     */
    captain?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Player
     */
    rookie?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Player
     */
    shootsCatches?: PlayerShootsCatchesEnum;
    /**
     * 
     * @type {string}
     * @memberof Player
     */
    rosterStatus?: string;
    /**
     * 
     * @type {PlayerCurrentTeam}
     * @memberof Player
     */
    currentTeam?: PlayerCurrentTeam;
    /**
     * 
     * @type {DraftProspectPrimaryPosition}
     * @memberof Player
     */
    primaryPosition?: DraftProspectPrimaryPosition;
}

/**
    * @export
    * @enum {string}
    */
export enum PlayerShootsCatchesEnum {
    L = 'L',
    R = 'R'
}

