/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PlayerStatsStat
 */
export interface PlayerStatsStat {
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    timeOnIce?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    assists?: string;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    goals?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    pim?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    shots?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    games?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    hits?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    powerPlayGoals?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    powerPlayPoints?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    powerPlayTimeOnIce?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    evenTimeOnIce?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    penaltyMinutes?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    faceOffPct?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    shotPct?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    gameWinningGoals?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    overTimeGoals?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    shortHandedGoals?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    shortHandedPoints?: number;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    shortHandedTimeOnIce?: string;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    blocked?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    plusMinus?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    points?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    shifts?: number;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    timeOnIcePerGame?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    evenTimeOnIcePerGame?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    shortHandedTimeOnIcePerGame?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    powerPlayTimeOnIcePerGame?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    rankPowerPlayGoals?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    rankBlockedShots?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    rankAssists?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    rankShotPct?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    rankGoals?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    rankHits?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    rankPenaltyMinutes?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    rankShortHandedGoals?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    rankPlusMinus?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    rankShots?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    rankPoints?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    rankOvertimeGoals?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    rankGamesPlayed?: string;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    goalsInFirstPeriod?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    goalsInSecondPeriod?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    goalsInThirdPeriod?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    goalsTrailingByOne?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    goalsTrailingByTwo?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    goalsTrailingByThreePlus?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    goalsWhenTied?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    goalsLeadingByOne?: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    goalsLeadingByTwo?: number;
}
