/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DraftProspectPrimaryPosition } from './draft-prospect-primary-position';
import { RosterPerson } from './roster-person';
/**
 * 
 * @export
 * @interface Roster
 */
export interface Roster {
    /**
     * 
     * @type {RosterPerson}
     * @memberof Roster
     */
    person?: RosterPerson;
    /**
     * 
     * @type {number}
     * @memberof Roster
     */
    jerseyNumber?: number;
    /**
     * 
     * @type {DraftProspectPrimaryPosition}
     * @memberof Roster
     */
    position?: DraftProspectPrimaryPosition;
}
