/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ScheduleDay } from './schedule-day';
/**
 * 
 * @export
 * @interface Schedule
 */
export interface Schedule {
    /**
     * 
     * @type {string}
     * @memberof Schedule
     */
    copyright?: string;
    /**
     * 
     * @type {number}
     * @memberof Schedule
     */
    totalItems?: number;
    /**
     * 
     * @type {number}
     * @memberof Schedule
     */
    totalEvents?: number;
    /**
     * 
     * @type {number}
     * @memberof Schedule
     */
    totalGames?: number;
    /**
     * 
     * @type {number}
     * @memberof Schedule
     */
    totalMatches?: number;
    /**
     * 
     * @type {number}
     * @memberof Schedule
     */
    wait?: number;
    /**
     * 
     * @type {Array<ScheduleDay>}
     * @memberof Schedule
     */
    dates?: Array<ScheduleDay>;
}
