/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ScheduleGame } from './schedule-game';
/**
 * 
 * @export
 * @interface ScheduleDay
 */
export interface ScheduleDay {
    /**
     * 
     * @type {string}
     * @memberof ScheduleDay
     */
    date?: string;
    /**
     * 
     * @type {number}
     * @memberof ScheduleDay
     */
    totalItems?: number;
    /**
     * 
     * @type {number}
     * @memberof ScheduleDay
     */
    totalEvents?: number;
    /**
     * 
     * @type {number}
     * @memberof ScheduleDay
     */
    totalGames?: number;
    /**
     * 
     * @type {number}
     * @memberof ScheduleDay
     */
    totalMatches?: number;
    /**
     * 
     * @type {Array<ScheduleGame>}
     * @memberof ScheduleDay
     */
    games?: Array<ScheduleGame>;
    /**
     * 
     * @type {Array<any>}
     * @memberof ScheduleDay
     */
    events?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof ScheduleDay
     */
    matches?: Array<any>;
}
