/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GameGameDataStatus } from './game-game-data-status';
import { GameGameDataVenue } from './game-game-data-venue';
import { GameLinescore } from './game-linescore';
import { ScheduleGameContent } from './schedule-game-content';
import { ScheduleGameTeams } from './schedule-game-teams';
import { ScheduleGameTickets } from './schedule-game-tickets';
import { GamePlay } from './game-play';
/**
 * 
 * @export
 * @interface ScheduleGame
 */
export interface ScheduleGame {
    /**
     * 
     * @type {number}
     * @memberof ScheduleGame
     */
    gamePk?: number;
    /**
     * 
     * @type {string}
     * @memberof ScheduleGame
     */
    link?: string;
    /**
     * 
     * @type {string}
     * @memberof ScheduleGame
     */
    gameType?: string;
    /**
     * 
     * @type {string}
     * @memberof ScheduleGame
     */
    season?: string;
    /**
     * 
     * @type {Date}
     * @memberof ScheduleGame
     */
    gameDate?: Date;
    /**
     * 
     * @type {GameGameDataStatus}
     * @memberof ScheduleGame
     */
    status?: GameGameDataStatus;
    /**
     * 
     * @type {ScheduleGameTeams}
     * @memberof ScheduleGame
     */
    teams?: ScheduleGameTeams;
    /**
     * 
     * @type {GameLinescore}
     * @memberof ScheduleGame
     */
    linescore?: GameLinescore;
    /**
     * 
     * @type {GameGameDataVenue}
     * @memberof ScheduleGame
     */
    venue?: GameGameDataVenue;
    /**
     * 
     * @type {Array<ScheduleGameTickets>}
     * @memberof ScheduleGame
     */
    tickets?: Array<ScheduleGameTickets>;
    /**
     * 
     * @type {ScheduleGameContent}
     * @memberof ScheduleGame
     */
    content?: ScheduleGameContent;
    /**
     * 
     * @type {ScoringPlay}
     * @memberof ScheduleGame
     */
        scoringPlays?: Array<GamePlay>
}
