/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ScheduleGameTeamsAwayLeagueRecord } from './schedule-game-teams-away-league-record';
import { ScheduleGameTeamsAwayTeam } from './schedule-game-teams-away-team';
/**
 * 
 * @export
 * @interface ScheduleGameTeamsAway
 */
export interface ScheduleGameTeamsAway {
    /**
     * 
     * @type {ScheduleGameTeamsAwayLeagueRecord}
     * @memberof ScheduleGameTeamsAway
     */
    leagueRecord?: ScheduleGameTeamsAwayLeagueRecord;
    /**
     * 
     * @type {number}
     * @memberof ScheduleGameTeamsAway
     */
    score?: number;
    /**
     * 
     * @type {ScheduleGameTeamsAwayTeam}
     * @memberof ScheduleGameTeamsAway
     */
    team?: ScheduleGameTeamsAwayTeam;
}
