/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PlayerCurrentTeam } from './player-current-team';
import { ScheduleGameTeamsHomeLeagueRecord } from './schedule-game-teams-home-league-record';
/**
 * 
 * @export
 * @interface ScheduleGameTeamsHome
 */
export interface ScheduleGameTeamsHome {
    /**
     * 
     * @type {ScheduleGameTeamsHomeLeagueRecord}
     * @memberof ScheduleGameTeamsHome
     */
    leagueRecord?: ScheduleGameTeamsHomeLeagueRecord;
    /**
     * 
     * @type {number}
     * @memberof ScheduleGameTeamsHome
     */
    score?: number;
    /**
     * 
     * @type {PlayerCurrentTeam}
     * @memberof ScheduleGameTeamsHome
     */
    team?: PlayerCurrentTeam;
}
