/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PlayerCurrentTeam } from './player-current-team';
import { ScheduleGameTeamsHomeLeagueRecord } from './schedule-game-teams-home-league-record';
import { StandingsStreak } from './standings-streak';
/**
 * 
 * @export
 * @interface StandingsTeamRecords
 */
export interface StandingsTeamRecords {
    /**
     * 
     * @type {PlayerCurrentTeam}
     * @memberof StandingsTeamRecords
     */
    team?: PlayerCurrentTeam;
    /**
     * 
     * @type {ScheduleGameTeamsHomeLeagueRecord}
     * @memberof StandingsTeamRecords
     */
    leagueRecord?: ScheduleGameTeamsHomeLeagueRecord;
    /**
     * 
     * @type {number}
     * @memberof StandingsTeamRecords
     */
    goalsAgainst?: number;
    /**
     * 
     * @type {number}
     * @memberof StandingsTeamRecords
     */
    goalsScored?: number;
    /**
     * 
     * @type {number}
     * @memberof StandingsTeamRecords
     */
    points?: number;
    /**
     * 
     * @type {string}
     * @memberof StandingsTeamRecords
     */
    divisionRank?: string;
    /**
     * 
     * @type {string}
     * @memberof StandingsTeamRecords
     */
    conferenceRank?: string;
    /**
     * 
     * @type {string}
     * @memberof StandingsTeamRecords
     */
    leagueRank?: string;
    /**
     * 
     * @type {string}
     * @memberof StandingsTeamRecords
     */
    wildCardRank?: string;
    /**
     * 
     * @type {number}
     * @memberof StandingsTeamRecords
     */
    row?: number;
    /**
     * 
     * @type {number}
     * @memberof StandingsTeamRecords
     */
    gamesPlayed?: number;
    /**
     * 
     * @type {StandingsStreak}
     * @memberof StandingsTeamRecords
     */
    streak?: StandingsStreak;
    /**
     * 
     * @type {Date}
     * @memberof StandingsTeamRecords
     */
    lastUpdated?: Date;
}
