/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DivisionConference } from './division-conference';
import { StandingsDivision } from './standings-division';
import { StandingsLeague } from './standings-league';
import { StandingsTeamRecords } from './standings-team-records';
/**
 * 
 * @export
 * @interface StandingsRecords
 */
export interface StandingsRecords {
    /**
     * 
     * @type {string}
     * @memberof StandingsRecords
     */
    standingsType?: StandingsRecordsStandingsTypeEnum;
    /**
     * 
     * @type {StandingsLeague}
     * @memberof StandingsRecords
     */
    league?: StandingsLeague;
    /**
     * 
     * @type {StandingsDivision}
     * @memberof StandingsRecords
     */
    division?: StandingsDivision;
    /**
     * 
     * @type {DivisionConference}
     * @memberof StandingsRecords
     */
    conference?: DivisionConference;
    /**
     * 
     * @type {Array<StandingsTeamRecords>}
     * @memberof StandingsRecords
     */
    teamRecords?: Array<StandingsTeamRecords>;
}

/**
    * @export
    * @enum {string}
    */
export enum StandingsRecordsStandingsTypeEnum {
    RegularSeason = 'regularSeason'
}

