/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TeamNextGameScheduleTeamsAway } from './team-next-game-schedule-teams-away';
import { TeamNextGameScheduleTeamsHome } from './team-next-game-schedule-teams-home';
/**
 * 
 * @export
 * @interface TeamNextGameScheduleTeams
 */
export interface TeamNextGameScheduleTeams {
    /**
     * 
     * @type {TeamNextGameScheduleTeamsAway}
     * @memberof TeamNextGameScheduleTeams
     */
    away?: TeamNextGameScheduleTeamsAway;
    /**
     * 
     * @type {TeamNextGameScheduleTeamsHome}
     * @memberof TeamNextGameScheduleTeams
     */
    home?: TeamNextGameScheduleTeamsHome;
}
