/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PlayerCurrentTeam } from './player-current-team';
import { TeamNextGameScheduleTeamsHomeLeagueRecord } from './team-next-game-schedule-teams-home-league-record';
/**
 * 
 * @export
 * @interface TeamNextGameScheduleTeamsHome
 */
export interface TeamNextGameScheduleTeamsHome {
    /**
     * 
     * @type {TeamNextGameScheduleTeamsHomeLeagueRecord}
     * @memberof TeamNextGameScheduleTeamsHome
     */
    leagueRecord?: TeamNextGameScheduleTeamsHomeLeagueRecord;
    /**
     * 
     * @type {number}
     * @memberof TeamNextGameScheduleTeamsHome
     */
    score?: number;
    /**
     * 
     * @type {PlayerCurrentTeam}
     * @memberof TeamNextGameScheduleTeamsHome
     */
    team?: PlayerCurrentTeam;
}
