/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TeamNextGameScheduleGames } from './team-next-game-schedule-games';
/**
 * 
 * @export
 * @interface TeamNextGameScheduleDates
 */
export interface TeamNextGameScheduleDates {
    /**
     * 
     * @type {string}
     * @memberof TeamNextGameScheduleDates
     */
    date?: string;
    /**
     * 
     * @type {number}
     * @memberof TeamNextGameScheduleDates
     */
    totalItems?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamNextGameScheduleDates
     */
    totalEvents?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamNextGameScheduleDates
     */
    totalGames?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamNextGameScheduleDates
     */
    totalMatches?: number;
    /**
     * 
     * @type {Array<TeamNextGameScheduleGames>}
     * @memberof TeamNextGameScheduleDates
     */
    games?: Array<TeamNextGameScheduleGames>;
    /**
     * 
     * @type {Array<any>}
     * @memberof TeamNextGameScheduleDates
     */
    events?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof TeamNextGameScheduleDates
     */
    matches?: Array<any>;
}
