/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TeamStatsStats } from './team-stats-stats';
/**
 * 
 * @export
 * @interface TeamStats
 */
export interface TeamStats {
    /**
     * 
     * @type {string}
     * @memberof TeamStats
     */
    copyright?: string;
    /**
     * 
     * @type {Array<TeamStatsStats>}
     * @memberof TeamStats
     */
    stats?: Array<TeamStatsStats>;
}
