/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GameGameDataVenue } from './game-game-data-venue';
import { ScheduleGameContent } from './schedule-game-content';
import { TeamNextGameScheduleStatus } from './team-next-game-schedule-status';
import { TeamNextGameScheduleTeams } from './team-next-game-schedule-teams';
/**
 * 
 * @export
 * @interface TeamNextGameScheduleGames
 */
export interface TeamNextGameScheduleGames {
    /**
     * 
     * @type {number}
     * @memberof TeamNextGameScheduleGames
     */
    gamePk?: number;
    /**
     * 
     * @type {string}
     * @memberof TeamNextGameScheduleGames
     */
    link?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamNextGameScheduleGames
     */
    gameType?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamNextGameScheduleGames
     */
    season?: string;
    /**
     * 
     * @type {Date}
     * @memberof TeamNextGameScheduleGames
     */
    gameDate?: Date;
    /**
     * 
     * @type {TeamNextGameScheduleStatus}
     * @memberof TeamNextGameScheduleGames
     */
    status?: TeamNextGameScheduleStatus;
    /**
     * 
     * @type {TeamNextGameScheduleTeams}
     * @memberof TeamNextGameScheduleGames
     */
    teams?: TeamNextGameScheduleTeams;
    /**
     * 
     * @type {GameGameDataVenue}
     * @memberof TeamNextGameScheduleGames
     */
    venue?: GameGameDataVenue;
    /**
     * 
     * @type {ScheduleGameContent}
     * @memberof TeamNextGameScheduleGames
     */
    content?: ScheduleGameContent;
}
