/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TeamStatsSplits } from './team-stats-splits';
import { TeamStatsType } from './team-stats-type';
/**
 * 
 * @export
 * @interface TeamStatsStats
 */
export interface TeamStatsStats {
    /**
     * 
     * @type {TeamStatsType}
     * @memberof TeamStatsStats
     */
    type?: TeamStatsType;
    /**
     * 
     * @type {Array<TeamStatsSplits>}
     * @memberof TeamStatsStats
     */
    splits?: Array<TeamStatsSplits>;
}
