/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DivisionConference } from './division-conference';
import { Franchise } from './franchise';
import { StandingsDivision } from './standings-division';
import { TeamNextGameSchedule } from './team-next-game-schedule';
import { TeamRoster } from './team-roster';
import { Venue } from './venue';
import { TeamColors } from './team-colors'
/**
 * 
 * @export
 * @interface Team
 */
export interface Team {
    /**
     * 
     * @type {number}
     * @memberof Team
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    link?: string;
    /**
     * 
     * @type {Venue}
     * @memberof Team
     */
    venue?: Venue;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    abbreviation?: string;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    triCode?: string;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    teamName?: string;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    locationName?: string;
    /**
     * 
     * @type {number}
     * @memberof Team
     */
    firstYearOfPlay?: number;
    /**
     * 
     * @type {StandingsDivision}
     * @memberof Team
     */
    division?: StandingsDivision;
    /**
     * 
     * @type {DivisionConference}
     * @memberof Team
     */
    conference?: DivisionConference;
    /**
     * 
     * @type {Franchise}
     * @memberof Team
     */
    franchise?: Franchise;
    /**
     * 
     * @type {TeamRoster}
     * @memberof Team
     */
    roster?: TeamRoster;
    /**
     * 
     * @type {TeamNextGameSchedule}
     * @memberof Team
     */
    nextGameSchedule?: TeamNextGameSchedule;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    shortName?: string;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    officialSiteUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof Team
     */
    franchiseId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Team
     */
    active?: boolean;
    /**
     * 
     * @type {TeamColors}
     * @memberof Team
     */
    colors?: TeamColors;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    logo?: string;
}
