/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TeamNextGameScheduleDates } from './team-next-game-schedule-dates';
/**
 * 
 * @export
 * @interface TeamNextGameSchedule
 */
export interface TeamNextGameSchedule {
    /**
     * 
     * @type {number}
     * @memberof TeamNextGameSchedule
     */
    totalItems?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamNextGameSchedule
     */
    totalEvents?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamNextGameSchedule
     */
    totalGames?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamNextGameSchedule
     */
    totalMatches?: number;
    /**
     * 
     * @type {Array<TeamNextGameScheduleDates>}
     * @memberof TeamNextGameSchedule
     */
    dates?: Array<TeamNextGameScheduleDates>;
}
