/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TeamStatsStat
 */
export interface TeamStatsStat {
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    gamesPlayed?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    wins?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    losses?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    ot?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    pts?: number;
    /**
     * 
     * @type {string}
     * @memberof TeamStatsStat
     */
    ptPctg?: string;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    goalsPerGame?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    goalsAgainstPerGame?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    evGGARatio?: number;
    /**
     * 
     * @type {string}
     * @memberof TeamStatsStat
     */
    powerPlayPercentage?: string;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    powerPlayGoals?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    powerPlayGoalsAgainst?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    powerPlayOpportunities?: number;
    /**
     * 
     * @type {string}
     * @memberof TeamStatsStat
     */
    penaltyKillPercentage?: string;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    shotsPerGame?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    shotsAllowed?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    winScoreFirst?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    winOppScoreFirst?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    winLeadFirstPer?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    winLeadSecondPer?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    winOutshootOpp?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    winOutshotByOpp?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    faceOffsTaken?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    faceOffsWon?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    faceOffsLost?: number;
    /**
     * 
     * @type {string}
     * @memberof TeamStatsStat
     */
    faceOffWinPercentage?: string;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    shootingPctg?: number;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    savePctg?: number;
}
