/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PlayerCurrentTeam } from './player-current-team';
import { TeamStatsStat } from './team-stats-stat';
/**
 * 
 * @export
 * @interface TeamStatsSplits
 */
export interface TeamStatsSplits {
    /**
     * 
     * @type {TeamStatsStat}
     * @memberof TeamStatsSplits
     */
    stat?: TeamStatsStat;
    /**
     * 
     * @type {PlayerCurrentTeam}
     * @memberof TeamStatsSplits
     */
    team?: PlayerCurrentTeam;
}
