<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="15.0.1" />
		<PackageReference Include="Azure.Storage.Blobs" Version="12.24.0" />
		<PackageReference Include="Azure.Storage.Queues" Version="12.24.0" />
		<PackageReference Include="DotNetEnv" Version="3.1.1" />
		<PackageReference Include="EfCore.SchemaCompare" Version="8.2.0" />
		<PackageReference Include="FirebaseAdmin" Version="3.1.0" />
		<PackageReference Include="MediatR" Version="13.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.20" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.21">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.21">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.21">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.21">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.10" />
		<PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="9.0.10" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.1" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
		<PackageReference Include="StackExchange.Redis" Version="2.9.32" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DraftPuck.Application\DraftPuck.Application.csproj" />
		<ProjectReference Include="..\DraftPuck.Shared\DraftPuck.Shared.csproj">
			<PrivateAssets>all</PrivateAssets>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="NewFolder\" />
	</ItemGroup>

</Project>
