interface UserNotificationPreferencesRequestModel {
  drinkReceivedNotificationPreference: NotificationPreference
  drinkAwardedNotificationPreference: NotificationPreference
  chatNotificationPreference: NotificationPreference
}
