name: Discord Notification

on:
  push:
    branches:
      - main
      - develop

jobs:
  discord-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_USERNAME: "DevBot"
          DISCORD_AVATAR: "https://draftpuck.com/img/logo-icon-only-2.png"
        with:
          args: '🚀 New push to **{{ EVENT_PAYLOAD.repository.full_name }}** on `{{ EVENT_PAYLOAD.ref }}`. \n\n**Commit:** {{ EVENT_PAYLOAD.head_commit.message }} \n👉 [View Diff]({{ EVENT_PAYLOAD.compare }})'