name: Discord Notification

on:
  push:
    branches:
      - develop
      - main

jobs:
  discord-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_USERNAME: "DevBot"
          DISCORD_AVATAR: "https://draftpuck.com/img/logo-icon-only-2.png"
        with:
          args: |
            A commit has been pushed:
              **Target:** `{{ EVENT_PAYLOAD.ref }}`
              **Commit:** {{ EVENT_PAYLOAD.head_commit.message }}
              ([View Diff]({{ EVENT_PAYLOAD.compare }}))